### ISSUE TITLE
CUDA out of memory. 

### ISSUE THREAD

**Issue by wxr521314** [rixez/Brats21_KAIST_MRI_Lab#2]
Hi :
Thank you for sharing, your work is amazing.
I am running nnUNet_train 3d_fullres nnUNetTrainerV2BraTSRegions_DA4_BN_BD_largeUnet_Groupnorm Task500_Colon 0 --npz
There was a problem RuntimeError: CUDA out of memory. Tried to allocate 1.17 GiB (GPU 0; 11.91 GiB total capacity; 10.92 GiB already allocated; 18.88 MiB free; 11.04 GiB reserved in total by PyTorch)

I want to know how much GPU is needed for training. I only have 12G. If 12G is not enough, can I train in other ways? ?

Best wishes

**Comment by rixez** [comment]
Hi @wxr521314,
Thanks for your interest!
For that configuration and a batch size of 2, you need about 18GB of GPU memory.
You can try reducing the batch size to 1 by modifying the plans file `plans.pkl` in the trainer folder.
If that doesn't work, you can try reducing the size of the network.
I hope that will work.

**Comment by wxr521314** [comment]
Hi,
Thank you. 
I have multiple Gpus and I was wondering if I could train with multiple Gpus. How do I do that? 
Also, I trained, nnUNetTrainerV2BraTSRegions_DA4_BN_BD_largeUnet, each epoch about 1400 s, is this normal?

**Comment by wxr521314** [comment]
Hi how do I change batch_size? PKL can not be modified, where should I modify in the program?

**Comment by rixez** [comment]
Hi @wxr521314, to answer your questions:
> Hi, Thank you. I have multiple Gpus and I was wondering if I could train with multiple Gpus. How do I do that? Also, I trained, nnUNetTrainerV2BraTSRegions_DA4_BN_BD_largeUnet, each epoch about 1400 s, is this normal?

I haven't tried training with multiple GPU but following nnUNet's guide, you can replace `nnUNet_train` with `nnUNet_train_DP` to do that. However, you also need to change the trainer and the UNet. The relevant files can be found here:
DP trainer:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d05fba87d392f4ab9cc6c64c1658688f7d27a3d0/nnunet/training/network_training/nnUNetTrainerV2_DP.py#L34
DP Unet:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d05fba87d392f4ab9cc6c64c1658688f7d27a3d0/nnunet/network_architecture/generic_UNet_DP.py#L26
The training time seems a bit long. It took about 200s per epoch on my machine. You can check this [link](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md) for some common performance issues. If your GPU is not at 100% utilization, you might want to move the data to a SSD or allocate more CPU threads for data augmentation. The training can sometimes become slower (probably due to data augmentation) and you can stop and resume training to hopefully fix the issue.

> Hi how do I change batch_size? PKL can not be modified, where should I modify in the program?

You can change the batch size in the PKL file using the codes below:
```
import pickle as pkl

with open('plans.pkl','rb') as f: 
    plans = pkl.load(f)

plans['plans_per_stage'][0]['batch_size'] =  1

with open('plans.pkl','wb') as f:
    pkl.dump(plans,f)

```
Let me know if that works.

**Comment by wxr521314** [comment]
I run this code, but I still get batch_size of 2
![image](https://user-images.githubusercontent.com/53425125/147642275-42226e03-e26f-4a40-837a-c89cbd2f37dd.png)
![image](https://user-images.githubusercontent.com/53425125/147642308-45d5e58f-5211-48ef-acd7-214eeaae1021.png)

**Comment by wxr521314** [comment]
I read the code of plans.pkl as follows:
![image](https://user-images.githubusercontent.com/53425125/147642852-a74c338b-8320-44ff-92b9-4adae0106b1c.png)

**Comment by rixez** [comment]
That seems weird. I ran the same codes on my machine and it works. Maybe try checking the codes and files again.

**Comment by wxr521314** [comment]
Thank you for your help.
      I have changed batch_size to 1, but nnunetplansv2.1_plans_3d. PKL should be changed instead of plans.pkl, actually plans.pkl is the copy of nnunetplansv2.1_plans_3D.pkl.
      I started training for each epoch about 700s.
      I also want to ask, where nnUNetTrainerV2BraTSRegions_DA4_BN_BD and nnUNetTrainerV2BraTSRegions_DA4_BN_BD_largeUnet_Groupnorm, I don't see it in network_training.
![image](https://user-images.githubusercontent.com/53425125/147809467-1a26cb1f-e19a-4993-b1a6-bb97af924d3e.png)


What kind of command should I type if I want to train BL+GN and BL+AA?

**Comment by rixez** [comment]
That's great! Sorry I didn't remember correctly and told you the wrong file.

You can check the codes  for the modified trainers in competitions_with_custom_Trainer/Brats2020:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d05fba87d392f4ab9cc6c64c1658688f7d27a3d0/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions_moreDA.py#L300

You can use the trainer nnUNetTrainerV2BraTSRegions_DA4_BN_BD_Groupnorm for BL+GN (just added):
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d652f9ad3065d1a477b7417c3fc0453f64564a0d/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions_moreDA.py#L300

For the BL + AA, use nnUNetTrainerV2BraTSRegions_DA4_BN_BD_normalUnet_axialattention:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d652f9ad3065d1a477b7417c3fc0453f64564a0d/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions_moreDA.py#L354
